# .github/workflows/python-data-upload.yml
# This workflow runs a Python script to upload data to Supabase.
# It can be triggered manually from the GitHub Actions tab.

name: Manual Supabase Data Upload

on:
  workflow_dispatch: # This allows you to run the workflow manually

jobs:
  upload-data:
    runs-on: ubuntu-latest # Use the latest available Ubuntu runner

    steps:
      - name: Check out repository code
        # This step downloads your code onto the runner
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        # This step sets up a Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        # This step installs the required Python libraries from requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run data upload script
        # This step executes your Python script
        # It uses the secrets you will configure in your repository settings
        run: python upload_script.py
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
